(function(){
  const boot=()=>{
    const dataEl=document.getElementById('students-data');
    const students=JSON.parse(dataEl?.textContent||'[]');
    const roleEl=document.getElementById('roleTitle'), jdEl=document.getElementById('jd'), minEl=document.getElementById('compMin'), maxEl=document.getElementById('compMax'), btn=document.getElementById('matchBtn'), results=document.getElementById('results');
    if(!students.length||!roleEl||!btn||!results)return;
    const css=`.tm-context{margin-top:14px;padding:12px;background:#F8FAFC;border:1px solid var(--line);border-radius:6px}.tm-context label{display:block;margin:0 0 6px}.tm-input{width:100%;box-sizing:border-box;font:13px Inter,sans-serif;color:var(--ink);background:#fff;border:1px solid var(--line);border-radius:6px;padding:9px 10px;margin-bottom:8px}.tm-help{font-size:10.5px;color:var(--muted);line-height:1.45;margin:-2px 0 8px}.tm-mode{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin-top:8px}.tm-mode button{border:1px solid var(--line);background:#fff;border-radius:5px;padding:7px 4px;font-size:10px;font-weight:600;cursor:pointer}.tm-mode button.active{background:var(--accent-soft);border-color:var(--accent);color:#174B82}.tm-output{margin-top:12px;background:#F8FBFE;border:1px solid #D7E6F5;border-left:3px solid var(--accent);border-radius:6px;padding:14px 16px}.tm-output h4{font-family:'IBM Plex Mono',monospace;font-size:9.5px;text-transform:uppercase;letter-spacing:.06em;color:var(--accent);margin:0 0 7px}.tm-output p{margin:0;font-size:13px;line-height:1.65;color:var(--ink);white-space:pre-line}.tm-output .tm-one{font-weight:600;line-height:1.5}.tm-actions{display:flex;gap:7px;margin-top:11px;flex-wrap:wrap}.tm-actions button{border:1px solid var(--line);background:#fff;border-radius:5px;padding:6px 9px;font-size:10.5px;font-weight:600;cursor:pointer}.tm-matchbox{margin-bottom:12px;padding:11px 13px;background:#F8FAFC;border:1px solid var(--line);border-radius:6px;font-size:11px;color:var(--ink-soft)}.tm-fit{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.tm-fit span{padding:4px 7px;border-radius:4px;font-size:10px;background:var(--sage-soft);color:#245541}`;
    const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
    const ctx=document.createElement('div');ctx.className='tm-context';ctx.innerHTML=`<label for="tmHighlight">Experience / context to highlight</label><input class="tm-input" id="tmHighlight" placeholder="e.g. Investment, Strategy, GTM"><div class="tm-help">The target role and the experience you want highlighted are separate inputs.</div><label for="tmLocation">Location constraint</label><input class="tm-input" id="tmLocation" placeholder="e.g. Bangalore, Mumbai or Remote"><div class="tm-help">Leave blank for any location. Separate multiple locations with commas.</div><label>Matching mode</label><div class="tm-mode" id="tmMode"><button type="button" data-mode="strict" class="active">Strict</button><button type="button" data-mode="balanced">Balanced</button><button type="button" data-mode="broad">Broad</button></div>`;
    const comp=maxEl?.closest('.comp-section');if(comp&&!document.getElementById('tmHighlight'))comp.insertAdjacentElement('afterend',ctx);
    let mode='strict';document.getElementById('tmMode')?.querySelectorAll('button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('#tmMode button').forEach(x=>x.classList.toggle('active',x===b));});
    const norm=s=>String(s||'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9₹%+./ -]/g,' ').replace(/\s+/g,' ').trim();
    const toks=s=>norm(s).split(/[^a-z0-9]+/).filter(x=>x.length>2);
    const aliases={bangalore:['bangalore','bengaluru'],delhi:['delhi','new delhi','gurgaon','gurugram','noida'],mumbai:['mumbai','bombay'],hyderabad:['hyderabad'],pune:['pune'],chennai:['chennai'],kolkata:['kolkata'],remote:['remote','wfh','work from home']};
    const locOk=(s,req)=>{if(!req.length)return true;const raw=norm([s.locationPref,s.city,s.ffNotes,s.hardConstraints].join(' '));if(/any location|any city|open to all|anywhere/.test(raw))return true;return req.some(r=>(aliases[r]||[r]).some(v=>raw.includes(v)));};
    const compOk=(s,min,max)=>{const t=parseFloat(String(s.targetComp||'').replace(/[^0-9.]/g,''));return !(Number.isFinite(t)&&((Number.isFinite(min)&&t<min)||(Number.isFinite(max)&&t>max)));};
    const score=(s,role,jd,hi)=>{const corpus=norm([s.rolesToSource,s.domain,s.minor1,s.minor2,s.functionalRTW,s.sectoralRTW,s.successTrack,s.resumeText,s.ffNotes,s.remarks].join(' '));const count=a=>a.filter(t=>corpus.includes(t)).length;const r=count(toks(role)),j=count(toks(jd)),h=count(toks(hi));return r*8+Math.min(j,14)*3+h*10+(r?8:0)};
    const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
    const evidence=s=>{const t=s.resumeText||'';const ss=t.split(/(?<=[.!?])\s+|\n+/).filter(Boolean);const n=ss.filter(x=>/\d|₹|\$|%|Cr|Lakh|MRR|ARR|AUM|revenue|clients|customers|leads/i.test(x));return(n.length?n:ss).slice(0,4).join(' ')};
    const build=()=>{const roles=(roleEl.value||'').split(',').map(x=>x.trim()).filter(Boolean),role=roles.join(' '),jd=(jdEl?.value||'').trim(),hi=(document.getElementById('tmHighlight')?.value||'').trim(),loc=(document.getElementById('tmLocation')?.value||'').split(',').map(norm).filter(Boolean),min=parseFloat(minEl?.value||''),max=parseFloat(maxEl?.value||'');const rows=[],excluded=[];students.forEach(s=>{const cf=compOk(s,min,max),lf=locOk(s,loc),sc=score(s,role,jd,hi);if(mode==='strict'&&(!cf||!lf)){excluded.push({s,reason:!cf?'Comp constraint':!lf?'Location constraint':''});return}rows.push({s,sc:sc+(cf?8:-15)+(lf?8:-15)});});rows.sort((a,b)=>b.sc-a.sc);return{rows:rows.slice(0,25),excluded,roles,jd,hi,loc,min,max};};
    async function generate(s,d){const prompt=`You are a senior recruiter writing a sharp, high-conviction candidate pitch for a hiring manager.\n\nTARGET ROLE(S): ${d.roles.join(', ')||'Not specified'}\nEXPERIENCE / CONTEXT TO HIGHLIGHT: ${d.hi||'Choose the most relevant experience'}\nJOB DESCRIPTION:\n${d.jd||'Not provided'}\n\nCANDIDATE DATA:\n${JSON.stringify({name:s.name,rolesToSource:s.rolesToSource,domain:s.domain,experience:s.experience,locationPref:s.locationPref,targetComp:s.targetComp,successTrack:s.successTrack,resumeText:s.resumeText,ffNotes:s.ffNotes,remarks:s.remarks})}\n\nWRITING STYLE: Follow this structure: first establish who the candidate is and the breadth/relevance of their experience; then give 2-3 strongest proof points with concrete metrics; end by connecting the evidence to the target role. The result should feel like a recruiter-written recommendation, NOT a resume summary. Select only the most relevant experiences; do not list every job, date, or responsibility. Use company/project names only when they add credibility.\n\nBLURB RULES:\n- Write 3-4 crisp sentences, around 80-120 words.\n- Use 2-4 concrete metrics from the supplied resume/profile where available.\n- Prioritize outcomes: revenue, customers, deals, leads, growth, conversion, scale, interviews/research volume, operational ownership.\n- Metrics must be copied exactly from the supplied data. Never invent, estimate, round, or combine numbers.\n- Use the selected experience/context as the central proof point while positioning the candidate for the target role.\n- Avoid chronology, filler, generic adjectives, and resume-style semicolon chains.\n- Do not mention dates unless they materially establish relevance.\n- If a metric is unavailable, use a specific qualitative achievement rather than fabricating one.\n\nONE-LINER RULES:\n- Exactly one sentence, approximately 25 words (20-30 acceptable).\n- Include at least one concrete metric whenever one exists.\n- Lead with the candidate's strongest role-relevant identity and proof point.\n\nReturn ONLY:\nONE-LINER:\n<one sentence>\nBLURB:\n<3-4 sentences>`;const r=await fetch('/api/blurb',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt})});if(!r.ok)throw Error('Generation failed');const j=await r.json(),text=j.text||'';return{one:(text.match(/ONE-LINER:\s*([\s\S]*?)(?:\nBLURB:|$)/i)||[])[1]?.trim()||'',blurb:(text.match(/BLURB:\s*([\s\S]*)/i)||[])[1]?.trim()||text.trim()};}
    function render(d){const header=`<div class="tm-matchbox"><b>${d.rows.length} ranked candidates</b> · ${d.roles.length?esc(d.roles.join(' + ')):'role not specified'} · ${d.loc.length?esc(d.loc.join(', ')):'any location'}<div class="tm-fit"><span>Hard filters applied</span><span>Metrics prioritized</span><span>Role + context separated</span></div></div>`;const cards=d.rows.map((r,i)=>{const s=r.s;return `<div class="card tm-card" data-name="${esc(s.name)}"><div style="display:flex;justify-content:space-between"><div><div class="rank">#${i+1}</div><div class="name-block"><h3>${esc(s.name)}</h3><div class="domain-line">${esc(s.domain||s.rolesToSource||'')}</div></div></div><div style="text-align:right"><div class="score-num">${Math.max(1,Math.min(100,r.sc))}</div><div class="score-label">fit</div></div></div><div class="meta-grid"><div class="meta-item"><span>Comp</span><b>${esc(s.targetComp||'Not set')} LPA</b></div><div class="meta-item"><span>Location</span><b>${esc(s.locationPref||s.city||'Not set')}</b></div><div class="meta-item"><span>Priority</span><b>${esc(s.priority||'')}</b></div></div><details class="profile-more"><summary>Evidence</summary><div class="more-body"><p>${esc(evidence(s))}</p></div></details><div class="card-actions"><button class="btn btn-blurb tm-generate">Generate one-liner + blurb</button></div><div class="tm-output" style="display:none"><h4>One-liner</h4><p class="tm-one"></p><h4 style="margin-top:14px">Blurb</h4><p class="tm-blurb"></p><div class="tm-actions"><button class="tm-copy-one">Copy one-liner</button><button class="tm-copy-blurb">Copy blurb</button></div></div></div>`}).join('');results.innerHTML=header+cards+(d.excluded.length?`<div class="tm-excluded"><h4>Excluded by hard constraints</h4>${d.excluded.slice(0,10).map(x=>`<div class="tm-excluded-item"><b>${esc(x.s.name)}</b> · ${esc(x.reason)}</div>`).join('')}</div>`:'');results.querySelectorAll('.tm-card').forEach(card=>{const s=students.find(x=>x.name===card.dataset.name),b=card.querySelector('.tm-generate'),out=card.querySelector('.tm-output');b.onclick=async()=>{b.disabled=true;b.textContent='Generating…';out.style.display='block';try{const g=await generate(s,d);card.querySelector('.tm-one').textContent=g.one;card.querySelector('.tm-blurb').textContent=g.blurb;card.querySelector('.tm-copy-one').onclick=()=>navigator.clipboard.writeText(g.one);card.querySelector('.tm-copy-blurb').onclick=()=>navigator.clipboard.writeText(g.blurb)}catch(e){card.querySelector('.tm-one').textContent='Could not generate right now.'}finally{b.disabled=false;b.textContent='Regenerate one-liner + blurb'}}});}
    btn.addEventListener('click',()=>render(build()));
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
